# Generated by Django 4.2.8 on 2024-01-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1047_equipment_vin_number_and_more"),
        ("paperless_mail", "0023_remove_mailrule_filter_attachment_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailrule",
            name="assign_equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.equipment",
                verbose_name="assign this equipment",
            ),
        ),
        migrations.AddField(
            model_name="mailrule",
            name="assign_equipment_from",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Do not assign a correspondent"),
                    (2, "Use mail address"),
                    (3, "Use name (or mail address if not available)"),
                    (4, "Use correspondent selected below"),
                ],
                default=1,
                verbose_name="assign equipment from",
            ),
        ),
    ]
