# Generated by Django 4.2.8 on 2024-01-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1046_document_equipment_workflowaction_assign_equipment"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="vin_number",
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="workflowtrigger",
            name="filter_has_equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documents.equipment",
                verbose_name="has this equipment",
            ),
        ),
    ]
