# Generated by Django 4.2.8 on 2024-01-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1047_equipment_vin_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="Make",
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="equipment",
            name="Model",
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
