# Generated by Django 4.2.8 on 2024-01-11 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1048_equipment_make_equipment_model"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipment",
            old_name="Make",
            new_name="make",
        ),
        migrations.RenameField(
            model_name="equipment",
            old_name="Model",
            new_name="model",
        ),
    ]
